### ISSUE TITLE
v2.36.7 breaks Jumpcloud login flow

### ISSUE THREAD

**Issue by epalchan** [Versent/saml2aws#1041]
Version 2.36.7 fails Jumpcloud login flow after auth before MFA with- `Error unmarshalling XSRF response! invalid character '<' looking for beginning of value`

Downgrading to v2.36.6 allows auth as usual with no issues.

Re-configuring the profile yields the same results.

**Comment by johndutchover** [comment]
A couple ways to control updating:
- [Homebrew](https://github.com/Homebrew/brew)
```
brew pin saml2aws
```
-  [asdf](https://github.com/asdf-vm/asdf)
```
asdf plugin add saml2aws https://github.com/Versent/saml2aws
asdf install saml2aws 2.36.6
asdf global saml2aws 2.36.6
```

**Comment by mapkon** [comment]
Sorry folks! This is possibly being addressed in Does this fix https://github.com/Versent/saml2aws/issues/1041?

**Comment by mapkon** [comment]
The PR has been reverted

**Comment by pzilaro** [comment]
I am still getting the same error - Error unmarshalling XSRF response! invalid character '<' looking for beginning of value
Can someone please double check ?

**Comment by pzilaro** [comment]
> Version 2.36.7 fails Jumpcloud login flow after auth before MFA with- `Error unmarshalling XSRF response! invalid character '<' looking for beginning of value`
> 
> Downgrading to v2.36.6 allows auth as usual with no issues.
> 
> Re-configuring the profile yields the same results.

How did you downgrade to v2.36.6? I didnt see an an option to downgrade using brew.

**Comment by johndutchover** [comment]
> > Version 2.36.7 fails Jumpcloud login flow after auth before MFA with- `Error unmarshalling XSRF response! invalid character '<' looking for beginning of value`
> > Downgrading to v2.36.6 allows auth as usual with no issues.
> > Re-configuring the profile yields the same results.
> 
> How did you downgrade to v2.36.6? I didnt see an an option to downgrade using brew.

This will work:
```
curl -L https://raw.githubusercontent.com/Homebrew/homebrew-core/def3bb32ef868224695e1e30f0bfe470327af1bb/Formula/saml2aws.rb > saml2aws.rb
brew install saml2aws.rb
```
...and then you can `brew pin saml2aws` for now to keep it at v2.36.6

**Comment by maximveksler** [comment]
What's the eta for 2.36.8 please?

**Comment by mapkon** [comment]
v2.36.8 has been released.

**Comment by mapkon** [comment]
@maximveksler https://github.com/Versent/saml2aws/discussions/1048

**Comment by epalchan** [comment]
@mapkon I can confirm that 2.36.8 resolves the issue. 
Thank you.
