### ISSUE TITLE
Error authenticating using google

### ISSUE THREAD

**Issue by rverma-nikiai** [Versent/saml2aws#203]
After accepting yes on google prompt during sam2aws login
Getting exception
```
error authenticating to IdP: page is missing saml assertion
```

Did configure
```
account {
  URL: https://accounts.google.com/
  Username: rohit.verma@xxx.xx
  Provider: GoogleApps
  MFA: Auto
  SkipVerify: false
  AmazonWebservicesURN: urn:amazon:webservices
  SessionDuration: 3600
  Profile: default
}
```
with .aws/config file as
```
[default]
region = us-west-2
google_config.ask_role = False
google_config.keyring = False
google_config.duration = 43100
google_config.google_idp_id = C000000
google_config.role_arn = arn:aws:iam::0000000000000:role/root-sysadmin-delegate
google_config.google_sp_id = 0000000000
google_config.u2f_disabled = True
google_config.google_username = rohit.verma@xxx
```

**Comment by paulopontesm** [comment]
Did you find anything about this?
I have the same happening to me, but only with with the google prompt. If I disable it (and leave the sms for example) it works.

**Comment by paulopontesm** [comment]
I tried to dig a little bit more and today.

There is something around a 50% chance that I can login successfully without getting that error. It seems that on the last step (after clicking "Yes") sometimes I get a page with "Your sign-in attempt timed out. Resend the prompt to try again". 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3610528/45224742-a495be80-b2b2-11e8-9615-0704bdc201a9.png">

I can't confirm this 100% yet (because I get "too many attempts after a while and I have to stop playing) but I think that everytime I get the "timeout" error the response comes from the "Server: GSE" and every time I login successfully the response comes from the "Server: ESF". No idea if this is a cause or a consequence.

**Comment by jwitrick** [comment]
Not sure if this helps, but I followed this README: https://github.com/Versent/saml2aws/blob/master/pkg/provider/googleapps/README.md

and after changing my url from:
https://accounts.google.com/ -> https://accounts.google.com/o/saml2/initsso?idpid=<idprovier>&spid=<serviceID>&forceauthn=false

i am now able to authenticate successfully.

**Comment by kahyoung** [comment]
--verbose logs, for more information:

```
DEBU[0001] building provider                             command=login idpAccount="account {\n  URL: <omitted>\n  Username: <omitted>\n  Provider: GoogleApps\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 43200\n  Profile: default\n}"
Authenticating as <omitted> ...
DEBU[0001] HTTP Req                                      URL="<omitted></omitted>" http=client method=GET
DEBU[0001] HTTP Res                                      Status="200 OK" http=client
DEBU[0002] name: Page value: PasswordSeparationSignIn    provider=googleapps
DEBU[0002] name:  value:                                 provider=googleapps
DEBU[0002] name: gxf value: AFoagUWeC0IenpnSjPnWgvG9X1NwPPOkLQ:1538698132684  provider=googleapps
DEBU[0002] name: continue value: <omitted>&from_login=1&as=C68hAqD7J9JUDA4sBaF4sg  provider=googleapps
DEBU[0002] name: followup value: <omitted>&from_login=1&as=C68hAqD7J9JUDA4sBaF4sg  provider=googleapps
DEBU[0002] name: ltmpl value: popup                      provider=googleapps
DEBU[0002] name: scc value: 1                            provider=googleapps
DEBU[0002] name: sarp value: 1                           provider=googleapps
DEBU[0002] name: oauth value: 1                          provider=googleapps
DEBU[0002] name: ProfileInformation value:               provider=googleapps
DEBU[0002] name: SessionState value: <omitted>
DEBU[0002] name: flowName value: GlifWebSignIn           provider=googleapps
DEBU[0002] name: _utf8 value: ☃                          provider=googleapps
DEBU[0002] name: bgresponse value: js_disabled           provider=googleapps
DEBU[0002] name: Email value:                            provider=googleapps
DEBU[0002] name: signIn value: Next                      provider=googleapps
DEBU[0002] HTTP Req                                      URL="https://accounts.google.com/signin/v1/lookup" http=client method=POST
DEBU[0002] HTTP Res                                      Status="200 OK" http=client
DEBU[0002] name: Page value: PasswordSeparationSignIn    provider=googleapps
DEBU[0002] name: GALX value: iKU_Rd91UN4                 provider=googleapps
DEBU[0002] name: gxf value: AFoagUVgTu06s-ug2VHokFsIBzLmnwsk_g:1538698132941  provider=googleapps
DEBU[0002] name: continue value: <omitted>
DEBU[0002] name: ltmpl value: popup                      provider=googleapps
DEBU[0002] name: scc value: 1                            provider=googleapps
DEBU[0002] name: sarp value: 1                           provider=googleapps
DEBU[0002] name: checkedDomains value: youtube           provider=googleapps
DEBU[0002] name: checkConnection value:                  provider=googleapps
DEBU[0002] name: pstMsg value: 0                         provider=googleapps
DEBU[0002] name: oauth value: 1                          provider=googleapps
DEBU[0002] name: ProfileInformation value: APMTqunZCN0M1dtY3X3cJoQCdPcpqTwnVmaWU8fN6eKDSad7D7nNYoyBukC1OmthFwGrnO0vHICTjVRQ_gkHj4am6wc_BQjrE7CwiuaecBa7fqdge5zqk3_wBdZ2eSN2LnPpOqt_envNoGxEN0KgJ9TxiR_bjtWAYkdVcNNkckJTkgEHfEwSR2c  provider=googleapps
DEBU[0002] name: SessionState value: <omitted>  provider=googleapps
DEBU[0002] name: _utf8 value: ☃                          provider=googleapps
DEBU[0002] name: bgresponse value: js_disabled           provider=googleapps
DEBU[0002] name: Email value: <omitted>  provider=googleapps
DEBU[0002] name: signIn value: Sign in                   provider=googleapps
DEBU[0002] name: PersistentCookie value: yes             provider=googleapps
DEBU[0002] loginURL: https://accounts.google.com/signin/challenge/sl/password  provider=googleapps
DEBU[0002] HTTP Req                                      URL="https://accounts.google.com/signin/challenge/sl/password" http=client method=POST
DEBU[0002] HTTP Res                                      Status="200 OK" http=client
page is missing saml assertion
github.com/versent/saml2aws/pkg/provider/googleapps.(*Client).Authenticate
	/Users/markw/Code/go/src/github.com/versent/saml2aws/pkg/provider/googleapps/googleapps.go:71
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:65
main.main
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:125
runtime.main
	/usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:67
main.main
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:125
runtime.main
	/usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201
runtime.goexit
	/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333
```

**Comment by estahn** [comment]
I believe it's a captcha issue:
```
<label  for="logincaptcha" class="hidden-label">Enter the letters above</label>
<input  type="text"
       id="logincaptcha"
       name="logincaptcha"
       class="captcha "
       placeholder="Enter the letters above"
       title="Type the characters that you see or the numbers that you hear">
```

**Comment by volker48** [comment]
@estahn I've been having the same issue and I when I render the page where saml2aws is failing I'm also seeing a captcha. I'm not sure why some members of my team are able to login just fine, but a few us aren't.

**Comment by volker48** [comment]
This https://github.com/cevoaustralia/aws-google-auth is working fine as it display the captcha for you.

**Comment by estahn** [comment]
@volker48 @wolfeidau I spoke to Google Support and TL;DR is "Not our problem". I couldn't get an explanation why you would need a CAPTCHA if 2FA is enabled. Both require an active action from a human, so I don't see the point.

> Hello Enrico,
> 
> Thank you for your patience while my colleague transferred your case. I understand that your using the sml2aws client for CLI access to Amazon Web services, authenticated via your XXX account.
> 
> This is XXX on the Google Cloud API & SSO Team, and I'll be dealing with your issue. unfortunately, due to time zone differences, I'm unable to call to discuss your issue further but can ask a colleague to call you at a time of your choosing.
> 
> Google only support web based authentication for SAML apps, so CLI access is outside our scope of support. having said that, I reviewed the issue you referenced[1], and noticed that one poster[2] referenced another CLI AWS integration, which supports Captcha handling[3]. I'd recommend investigating this option, as Captcha is used for both login risk, and abuse verification, so is relevant even if two factor is enabled, and it's not possible to disable it.
> 
> If you have any other queries regarding this issue, please reply to this message, and I'd be happy to assist you further.
> 
> 
> Sincerely, 
> 
> XXX
> Google Cloud Support
> 
> [1] https://github.com/Versent/saml2aws/issues/203
> [2] https://github.com/Versent/saml2aws/issues/203#issuecomment-428231296
> [3] https://github.com/cevoaustralia/aws-google-auth

**Comment by mominosin** [comment]
FYI:
If you allow here, the error no longer exists.
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by Raffo** [comment]
@mominosin do you know what allowing on this link actually does?

**Comment by estahn** [comment]
> @mominosin do you know what allowing on this link actually does?

Nothing. I have tried multiple methods including contacting Google Support without success.

**Comment by gogrisohil** [comment]
You can try adding "Get Google prompt on all the phones you're signed in to" as a type of 2FA and that works for me.

**Comment by estahn** [comment]
The newest version for saml2aws should resolve this issue. I believe you can close this @wolfeidau

**Comment by arthurbryant** [comment]
Like @estahn said, after `brew upgrade saml2aws`, everything went back to normal. Thank you!

**Comment by rokka-n** [comment]
I went and tweaked all the little things mentioned in the thread, but still getting `"error authenticating to IdP: page is missing saml assertion"`

Is there anything special about google accounts managed with G Suite? I don't believe so... The web sso with the url working without any issues.

Any clues where to dig?

**Comment by rokka-n** [comment]
> I went and tweaked all the little things mentioned in the thread, but still getting `"error authenticating to IdP: page is missing saml assertion"`

Nevermind, the google thingly has some eventual consistency to it - started working after few days on its own.

**Comment by futurekill** [comment]
I'm still facing this issue. I'm the only one in my org that can auth via saml2aws.

**Comment by futurekill** [comment]
It may be related to this: https://github.com/cevoaustralia/aws-google-auth/issues/160

**Comment by sidewinder12s** [comment]
I think I've had some users running into this if they are _not_ using Google App Prompt. They also have TOTP and saml2aws never asks for it, it just fails out.

**Comment by nathandines** [comment]
I've just submitted PR #445 which should address this. Feel free to build from that and see how that goes for you.

**Comment by rakshit-jm** [comment]
Still facing this issue, especially when some of the attempts for login have failed.

**Comment by SurenNihalani** [comment]
I just faced this issue. how should I debug this?

**Comment by SurenNihalani** [comment]
<span class="Qx8Abe" id="errorMsg">Wrong code. Try again.</span

**Comment by amontalban** [comment]
I just came back from vacations, I tried to login and got this on `2.36.2`:

```
POST /signin/challenge/pwd/2?hl=en&loc=US HTTP/1.1                                                                                                                                                                                                             Host: accounts.google.com                                                                                                                                                                                                                                      User-Agent: saml2aws/1.0 (darwin arm64) Versent                                                                                                                                                                                                                
Content-Length: 606                                                                                                                                                                                                                                            Accept-Language: en-US                                                                                                                                                                                                                                         Content-Language: en-US                                                                                                                                                                                                                                        
Content-Type: application/x-www-form-urlencoded                                                                                                                                                                                                                Referer: https://accounts.google.com/signin/challenge/pwd/2                                                                                                                                                                                                    Accept-Encoding: gzip
```

```
HTTP/1.1 400 Bad Request
<p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins>
```

**Comment by vaibhavpandey2000** [comment]
still facing the issue, why this thread is closed without solution?
